[package]
name = "feishubot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.61"
env_logger = "0.9.0"
log = "0.4.17"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
